### ISSUE TITLE
Gatekeeper to security hub lamda fails

### ISSUE THREAD

**Issue by ds50421** [aws-samples/securityhub-k8s-policy-integration#1]
Is there an issue with lambda? Looks like lambda is not able to accpt format of audit report

We followed everystep ,changed runtime from 3.12,3.11 etc yet same error.

Our goal is to send gatekeeper violations to security hub.We followed same steps as in doc and changed policytype to gatekeeper

LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html

[ERROR] KeyError: 'violations'
Traceback (most recent call last):
File "/var/task/[lambda_function.py](http://disq.us/url?url=http%3A%2F%2Flambda_function.py%3Adq-abZFjwWVhRPZy0OTP8fDDh6A&cuid=4559555)", line 419, in lambda_handler
securityhub_findings = parse_gatekeeper_audit_report(
File "/var/task/[lambda_function.py](http://disq.us/url?url=http%3A%2F%2Flambda_function.py%3Adq-abZFjwWVhRPZy0OTP8fDDh6A&cuid=4559555)", line 358, in parse_gatekeeper_audit_report
violations = status["violations"]END RequestId: 80a80457-fe59-476a-8405-3b12f9c36580

**Comment by rinaudjaws** [comment]
Hello @ds50421, I'll try again to reproduce this issue for Gatekeeper. Could you let me know which Gatekeeper version are you running?

**Comment by ds50421** [comment]
Hi @rinaudjaws - we use 3.16.3 for gatekeeper.

**Comment by rinaudjaws** [comment]
Sorry for the delay on this issue, merged #2 to fix for the issue when no findings exist for that Gatekeeper constraint.

Could you confirm this fixed your issue?

**Comment by ds50421** [comment]
@rinaudjaws -Thank you for all help.Issue is solved,all events are sent to security hub.Lot of regards for getting this solution and helped automate this process.

One question: can you please check if we can have this solution in cloudformation so that we can deploy it as stackset(either via self managed or service managed).VPC,cluster and subnets can be parameterized.

{'apiVersion': 'constraints.gatekeeper.sh/v1beta1', 'items': [], 'kind': 'K8sPSPCapabilitiesList', 'metadata': {'continue': '', 'resourceVersion': '74329095'}}
{'apiVersion': 'constraints.gatekeeper.sh/v1beta1', 'items': [], 'kind': 'K8sPSPFlexVolumesList', 'metadata': {'continue': '', 'resourceVersion': '74329095'}}
{'apiVersion': 'constraints.gatekeeper.sh/v1beta1', 'items': [], 'kind': 'K8sRequiredLabelsList', 'metadata': {'continue': '', 'resourceVersion': '74329095'}}
[INFO]  2024-06-20T08:56:32.981Z     7723452c-ca9a-4dcc-92c4-5a440a818754   192 Findings imported to Security Hub

**Comment by rinaudjaws** [comment]
Glad to hear this is working! I'll close the issue then.

Created another issue to track the feature request as Stacksets: #3. Because of the VPC, subnets and SSG requirements, this can mean 1 / only works for public EKS endpoints out of the box 2 / use SSM to retrieve data per account / region 3 / Ask each team to fix parameters based on each region (not really user friendly). I would be interested to hear other alternatives or ideas in that issue! 

Regards,
